### ISSUE TITLE
Tables scroll too much on mobile in rgbasm(5)

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds-www#10]
Some tables in the RGBASM language description are too large, and cause overflow that breaks the page layout.

A content fix isn't the way to go, as I would prefer not to touch the previous versions' pages.

**Comment by zemzelett** [comment]
Can this issue be closed or is there something, that the merged pull request #26 didn't address?

**Comment by ISSOtm** [comment]
Nope, fixed by #26.
