### ISSUE TITLE
[Enhancement] Provide PDFs of the man pages

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds-www#12]
`mandoc` is able to produce PDF exports, so we should be able to serve those as well. They've been requested a couple times.

**Comment by bentley** [comment]
mandoc’s HTML output is much better than groff’s, but groff’s PDF output is much better than mandoc’s.

    $ groff -Tpdf -mdoc rgbasm.1 > rgbasm.pdf

**Comment by ISSOtm** [comment]
I'm concerned about `groff` not providing a table of contents, which is pretty much a requirement for `rgbasm(5)` due to its size...

**Comment by Rangi42** [comment]
[`groff` 4.3.6.4 Creating a table of contents](https://www.gnu.org/software/groff/manual/html_node/ms-TOC.html): "[The *Groff and Friends HOWTO](https://www.troff.org/TheGroffFriendsHowto.pdf)* includes a `sed` script *[12.2 Creating the Index]* that automatically inserts `XS` and `XE` macro entries after each heading in a document."

**Comment by ISSOtm** [comment]
It appears to be impossible to use these macros together with `-mdoc`. Plus, I checked, neither `groff` nor `mandoc` seem to generate PDF links, so a ToC wouldn't be useful anyway.
