### ISSUE TITLE
Change site design

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds-www#16]
It has been reported (at least by @zaidmade and @AntonioND) that the stylesheet needs to be reworked. (The former [forked the site](https://github.com/ZaidMade/rgbds-www/commit/04b29b4801ad9ff719f4acb8563e27ec0f85419c), though it's broken due to #15.)

- [x] Noisy background
- [ ] Hard-to-read font (in monospace)
- [ ] Improvable color scheme (debatable?)

Suggested fixes:

- ~~**Background**:~~
  - ~~Use solid color~~
  - ~~Use solid color behind text only~~
- **Font**:
  - Put `Roboto` in front
  - Use a different font?
- **Color scheme**:
  - Different navbar? See the fork linked to above
  - Change links colors?

**Comment by Rangi42** [comment]
Background fix:

```diff
 main {
 	margin: 0 auto;

 	max-width: $max-width;
 	// Prevent text from bumping sides on smaller windows
-	padding: 10px 20px 10px 10px;
+	padding: 10px 20px;
+ 	background: #EEE;
}
```

**Comment by avivace** [comment]
This could be closed / reopened in a similar fashion in the new repo, no @ISSOtm ?

See https://github.com/gbdev/rgbds-www/issues/27

**Comment by ISSOtm** [comment]
I don't think the issues listed here apply to the design over there. Do they?

**Comment by avivace** [comment]
I'm closing this as we migrated the entire stack to the React/Docusaurus version
