### ISSUE TITLE
rgbds.gbdev.io sitemap can't be submitted to google

### ISSUE THREAD

**Issue by avivace** [gbdev/rgbds-www#25]
Apologies if this is not the correct place to report errors on the generated website/documentation.

This is what I'm seeing on the Google Webmaster console for rgbds.gbdev.io:

![image](https://user-images.githubusercontent.com/14352721/127657671-e1d4d598-e12d-4b9d-a575-3375c1872dbe.png)

**Comment by ISSOtm** [comment]
Transferred to the website repo, no worries :p

Yeah, I tried submitting the sitemap some time ago, and it failed for the same reason—I've forgotten since then. I'm not quite sure why it's failing, though. The sitemap is automatically generated, too.

**Comment by pinobatch** [comment]
I'm pretty sure `/docs/` failed because it's not an absolute URL. From [General sitemap guidelines](https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap#general-guidelines):
> **Use consistent, fully-qualified URLs.** Google will crawl your URLs exactly as listed. For instance, if your site is at `https://www.example.com/`, don't specify a URL as `https://example.com/` (missing `www`) or `./mypage.html` (a relative URL).

**Comment by ISSOtm** [comment]
To try: set the URL config properties, see if the sitemap generator picks them up.

https://github.com/gbdev/rgbds-www/blob/9c688a50847c96a90e5c3067a1a7c07cbe47afa4/_config.yml#L16-L17

**Comment by ISSOtm** [comment]
... with these settings, my sitemap on localhost properly contains absolute URLs, so this is likely not it... I just updated the gems, though, so we'll see if those updates fix the issue.

**Comment by ISSOtm** [comment]
... nope, so I'll try setting them real quick. It's imo likely that GitHub overrides those *somehow*, causing the truncated URLs to appear.

**Comment by ISSOtm** [comment]
... nope. I reverted the commit (a quick force-push on *this* repo won't hurt anyone), but at this point we may have to report an issue to GitHub themselves—this doesn't seem to be on our side.

**Comment by ISSOtm** [comment]
[We just have to wait and see now](https://github.community/t/sitemap-generated-with-relative-urls-only/193062).

**Comment by ISSOtm** [comment]
Fixed by 0c9b420 :)

![image](https://user-images.githubusercontent.com/15271137/128749999-fd35575b-9374-4c61-a6e5-42a338a61842.png)

**Comment by avivace** [comment]
Great! Thanks @ISSOtm
