### ISSUE TITLE
CPU opcode reference page got changed?

### ISSUE THREAD

**Issue by elialm** [gbdev/rgbds-www#28]
I was just looking at the OP code reference and the wordings are, let's say, quite interesting. Someone changed the documentation to include meme references (see screenshot below). I searched for some strings in the repo, but couldn't find any matches, so I'm guessing some funny guy changed the HTML files on the server. It's very funny and all, but it's quite distracting. Can it be changed back?

![image](https://user-images.githubusercontent.com/43206514/161572302-08670b13-8bf7-4bc3-b823-8aa91ba33ce2.png)
![image](https://user-images.githubusercontent.com/43206514/161572381-ea74f23d-b307-4833-9f65-39afc8e675ec.png)
![image](https://user-images.githubusercontent.com/43206514/161572474-51964dc3-bb1b-4033-b24b-469e2a378188.png)

**Comment by ISSOtm** [comment]
Yeah, this is an April Fools release, you should use the previous release's documentation. You're not wrong that we forgot to revert the "lastest release" redirections, though—sorry about that!

**Comment by elialm** [comment]
Ah cool, np. It's still very funny and surprising to see it.
