### ISSUE TITLE
Anchor links are scrolled to behind the navbar

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds-www#3]
To fix this, the anchors should be moved up by the navbar's height. The question then becomes how to do this... JS could be used, but not everyone enables JS; we can't use a custom Jekyll plugin because GitHub Pages prevents it; and I didn't find such a plugin among the whitelisted ones.

An alternative would be making the main content scroll within itself, instead of the whole `<body>` scrolling; I'm however not sure how to achieve that.

**Comment by Rangi42** [comment]
To make only the main content scroll:

- Wrap `<main>` in a `<div>` with `overflow: auto; height: calc(100% - 51px);`
- Have `<body>` be `height: 100vh; overflow: hidden;`
- Edit `<aside>` to remove `position: fixed; top: 0; left: 0;`
- Edit `<main>` to remove its `margin-top: 51px;`

Also remove `max-width: 65em;` from `<html>` in doc.css.
