### ISSUE TITLE
seo: add open graph and twitter properties

### ISSUE THREAD

**Issue by avivace** [gbdev/rgbds-www#30]
- Add og:title and og:description to homepage and articles
- Add twitter specific tags for generating the cards

**Comment by ISSOtm** [comment]
`og:title` and `og:description` are automatically added by Docusaurus on every page that has a description; it should simply be set via MarkDown frontmatter:
```
---
title: (...)
description: (...)
---
```
For example, the main page has those, but the docs don't.
