### ISSUE TITLE
The "Game Boy Development resources" link is broken

### ISSUE THREAD

**Issue by ahrnbom** [gbdev/rgbds-www#31]
On the main page (https://rgbds.gbdev.io/), near the bottom, under "More", there's a link with the text "Game Boy Development resources" leading to  https://gbdev.io/list.html#introduction, which is a broken link. Maybe it should link to https://eldred.fr/gb-asm-tutorial/resources.html instead?

**Comment by avivace** [comment]
@ahrnbom thanks for the report! Refresh (CTRL+F5) and check again, I just fixed it
