### ISSUE TITLE
[Enhancement] Providing alternative styles

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds-www#4]
We could provide alternative styling, for example modifying the font size, providing a dark mode, and disabling text justification (I was told dyslexic people have trouble with it).
Additionally, it should be possible to use [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) to set the default color scheme, for example.

There are two problems:
1. How can we store this information at least during one browsing session? True persistence is probably not worth implementing, but it'd just be frustrating to have to reset these settings for every visit.
2. How do we provide toggles? Adding them to the navbar would increase the clutter, especially on mobile; plus, managing the drop-downs with the collapsed navbar would add complexity...

Problem 1 could be solved using some JS and browser storage, as I've seen some sites do.
For Problem 2, I'm thinking we could add some button at the bottom of the page, that'd open a drop-down/pop-up of toggles?

**Comment by zemzelett** [comment]
I'm working on this atm, is there any preference on a dark-mode color scheme other than mentioned in issue #14?

Oh, and for your points on the problems: I'd solve problem 1 with [Local Storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). Problem 2 i'd solve along the lines of what you pointed out.

**Comment by ISSOtm** [comment]
Ah, we are currently working on a complete overhaul of the site over at [rgbds-www2](https://github.com/gbdev/rgbds-www2), which does have dark mode support. This is where contributions should happen now, besides important fixes that shouldn't wait.

**Comment by zemzelett** [comment]
Ha, thanks for the heads up. Luckily i didn't do too much yet. :)

**Comment by avivace** [comment]
Closed in favor of https://github.com/gbdev/rgbds-www/issues/27, which already includes a dark mode.
