### ISSUE TITLE
"See also" links on man pages are broken

### ISSUE THREAD

**Issue by DaKnig** [gbdev/rgbds-www#45]
the website mentions the page rgbasm.5 multiple times, but links to a non existing page rgbds.5/rgbasm.5 which 404s...

**Comment by ISSOtm** [comment]
SDiscussion at gbdev/rgbds#1133

**Comment by Rangi42** [comment]
The man pages themselves are fine; the fix for this will be some change to rgbds-www. So this is the GitHub issue for resolving it.

**Comment by ISSOtm** [comment]
Copying what was said over there:

> The problem is that the URLs used to be served *without* a trailing slash, and then the relative links worked correctly. Something changed, and now trailing slashes are enforced by GitHub Pages; two possible fixes are to either add a `../`, or to use the full path from the root.
>
> Thoughts on which one is preferable?

> [Full paths] however require modifying the generated HTML, which is its own pile of problems...

**Comment by DaKnig** [comment]
any downsides to adding trailing slash?

**Comment by ISSOtm** [comment]
I've pinpointed what the "something" that changed is: I'm not sure why, but Docusaurus generates the pages [as `index.html` in directories](https://github.com/gbdev/rgbds-www/tree/47bf704730789e19836ede22eb1ff73c0666f83b/docs/rgbasm.1)! This is why GitHub enforces the trailing slash.

Is there a way to make Docusaurus... not do that? Worst case, we can run a post-process script that moves the pages appropriately, but then local setups would still be broken, among other things.
