### ISSUE TITLE
Finding a Windows build of `master` is confusing

### ISSUE THREAD

**Issue by pinobatch** [gbdev/rgbds-www#49]
I plan to use a feature added in <https://github.com/gbdev/rgbds/pull/1159> in a Game Boy project, and I want to know what to tell contributors who use Windows to install until RGBDS 0.6.2 comes out. I'm having trouble finding on the website how to obtain and install Windows executables of RGBDS `master` built by a GitHub Actions job. 

1. In <https://rgbds.gbdev.io/install>, under `Windows` then `"Plain" Windows`, follow "go here". **Broken.** This link leads to a nonexistent anchor `using-rgbds-master`.
2. In <https://rgbds.gbdev.io/install>, under `Windows` then `"Plain" Windows`, follow "use `master`", then follow "use our CI". **Broken.** This link leads back to `install` under a nonexistent anchor `using-our-ci`.

The correct answer appears to be this: In <https://rgbds.gbdev.io/install>, follow "using a development version", then scroll down to "Using our CI" and follow "made available on GitHub". Then under "workflow run results", follow the name of the most recent PR with a green check next to `master`, scroll down to "Artifacts", and then download `rgbds-canary-win64`.

Aside: The "go here" phrasing for the call to action is deprecated by a [W3C article](https://www.w3.org/QA/Tips/noClickHere), which claims that noun phrases make the clearest CTA. According to ["The problem with 'click here' and 'learn more' links" by Cynthia Marinakos](https://12ft.io/proxy?q=https%3A%2F%2Fuxdesign.cc%2Fthe-problem-with-click-here-and-learn-more-links-d01a0eba5cbd), it slows the reader and creates a feeling of risk. Answers to questions on [UX Stack Exchange](https://ux.stackexchange.com/q/12100/40840) and [Webmasters Stack Exchange](https://webmasters.stackexchange.com/q/7114/32632) explain what an author can do about "here" in links.

**Comment by avivace** [comment]
Yep, noticed this as well. Thanks for the pointers @pinobatch

This is part of https://github.com/gbdev/rgbds-www/pull/48

**Comment by pinobatch** [comment]
On Discord, avivace requested that I update the status of this report. I found this change first:
- In <https://rgbds.gbdev.io/install>, `"Plain" Windows` has become `None of those`.

1. Under `Windows` and then `None of those`, "go here" now points to [Using a development version](https://rgbds.gbdev.io/install/master), which I mentioned as the correct answer. My only remaining **nitpick** is a preference for labeling the link as a noun: "go to `master` instructions."
2. Under `Windows` and then `None of those`, "use `master`" points at the correct page, but at a nonexistent fragment `what` instead of the correct `master`. And in that "What is `master`?" section, "use our CI" still points at a nonexistent fragment. **Still broken.** It is currently <https://rgbds.gbdev.io/install#using-our-ci> and should be changed to <https://rgbds.gbdev.io/install/master#using-our-ci>.

Also the problem remains of [artifact download links working only for members of GitHub](https://github.com/actions/upload-artifact/issues/51).

**Comment by avivace** [comment]
> Also the problem remains of [artifact download links working only for members of GitHub](https://github.com/actions/upload-artifact/issues/51).

Is this what you're looking for @pinobatch ? https://nightly.link/gbdev/rgbds/workflows/testing/master

**Comment by ISSOtm** [comment]
Those seem to work on a browser that isn't logged in for me.

**Comment by pinobatch** [comment]
Directing users to `[rgbds-canary-mingw-win64.zip](https://nightly.link/gbdev/rgbds/workflows/testing/master/rgbds-canary-mingw-win64.zip)` on that page should work as long as nightly.link keeps working.

This issue won't affect me personally once 0.7 is out. It may start affecting me again if I end up having to depend on a `master`-only feature.
