### ISSUE TITLE
Add RGBDS-Live to the links

### ISSUE THREAD

**Issue by avivace** [gbdev/rgbds-www#50]
What about adding a "Try" or "Playground" link in the main navbar? (or in the main action buttons in the home page)?

Side question: should we fork rgbds-live?

**Comment by Rangi42** [comment]
[rgbds-live](https://daid.github.io/rgbds-live/) is still using rgbds 0.5.1 and lists its last copyright date as 2020. I don't think it's still maintained.

**Comment by ISSOtm** [comment]
That sounds fair to me if we can get rgbds-live maintained; @daid is not working on his GB projects anymore, but we still can contact him.

The available options are to fork rgbds-live and hopefully upstream the changes, fork it and treat our fork as the new upstream, or see with Daid about transferring ownership of the "root" repo.

**Comment by daid** [comment]
We moved the repo: https://github.com/gbdev/rgbds-live so should be easier to maintain by multiple people from there.
I haven't had a reason to update it, but it shouldn't be too complex to get a newer rgbds in.

**Comment by ISSOtm** [comment]
> Disadvantage we discovered afterwards, is that it breaks old links, so links need to updated from daid.github.io to gbdev.io

You can upload a placeholder repo that contains redirects: https://github.com/ISSOtm/gb-asm-tutorial

**Comment by avivace** [comment]
Thanks again @daid . We're working on modernising a bit the build process of rgbds-live. Once we update the rgbds version to 0.6.1 it'll be ready to be linked from the rgbds website
