### ISSUE TITLE
`RRA` & `RRAC` Carry Flag Docs Seem Incorrect

### ISSUE THREAD

**Issue by rsandor** [gbdev/rgbds-www#55]
According to the documentation for the GBZ80 instructions that is currently online:

- `RRA` fills the 8th bit with the value of the carry flag (aka: `C -> [7 -> 0] -> C`)
- `RRCA` fills the bit with a zero (aka: `0 -> [7 -> 0] -> C`)

However, according to what I am seeing when I actually assemble some code, the opposite is true:

- `RRA` fills the 8th bit with a zero (aka: `0 -> [7 -> 0] -> C`)
- `RRCA` fills it with the carry flag (aka: `C -> [7 -> 0] -> C`)

I am not sure if I am missing something here, or whatever, but I thought I would bring it to your attention.

**Comment by ISSOtm** [comment]
Are [the `master` docs](https://rgbds.gbdev.io/docs/master/gbz80.7/#RRA) clearer?
