### ISSUE TITLE
Set a social media preview image, instead of the logo icon

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds-www#64]
People often leave previews in Discord links, and https://rgbds.gbdev.io appears as its logo image, a low-res square RGB icon.

Looking at GitHub's "social media preview" feature, this HTML header content would suffice for Discord and Twitter at least:

```html
<meta name="twitter:image:src" content="https://rgbds.gbdev.io/preview.png" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="@github" />
<meta name="twitter:title" content="RGBDS: ..." />
<meta name="twitter:description" content="RGBDS: ..." />

<meta property="og:image" content="https://rgbds.gbdev.io/preview.png" />
<meta property="og:type" content="object" />
<meta property="og:site_name" content="GitHub" />
<meta property="og:url" content="https://rgbds.gbdev.io" />
<meta property="og:image:alt" content="RGBDS: ..." />
<meta property="og:title" content="RGBDS: ..." />
<meta property="og:description" content="RGBDS: ..." />
```

An example of its current appearance:

![image](https://github.com/gbdev/rgbds-www/assets/35663410/9a07d49e-036d-4228-8d84-110ab9ae9588)

**Comment by avivace** [comment]
What could we put instead of the logo?

**Comment by Rangi42** [comment]
An entire logo including the "RGBDS" text would be wider, so less relatively tall.

**Comment by avivace** [comment]
![image](https://github.com/gbdev/rgbds-www/assets/14352721/72295eec-b849-4468-8350-e1393dd0ceee)
Something like this?

**Comment by Rangi42** [comment]
Or with less margin:
![image](https://github.com/gbdev/rgbds-www/assets/35663410/6465bfd6-9b8d-44bf-a41f-d6252666a788)

**Comment by ISSOtm** [comment]
Agreed, that's a great idea!
