### ISSUE TITLE
confusing title sizes

### ISSUE THREAD

**Issue by avivace** [gbdev/rgbds-www#74]
![image](https://github.com/user-attachments/assets/01c5d8a5-c57e-429b-b484-95971e1f0cf7)
the h1/h2 in the body of the page are bigger than the page title

**Comment by Rangi42** [comment]
The page title ("Release information") is an `h1`; the body headings ("GitHub links", "Table of contents") are `h2`s.

Both `h1` and `h2` have the same `font-size` and `font-weight`. However, `h1` uses `font-family: "Akshar"`, which is not as wide/heavy as `h2`'s `font-family: "Akshar Medium"`.

**Comment by avivace** [comment]
Fixed in https://github.com/gbdev/rgbds-www/commit/33f1ccd1a05f69af38d63ed45c5aaa19356d7750
