### ISSUE TITLE
CMake Release builds

### ISSUE THREAD

**Issue by JL2210** [gbdev/rgbds-www#9]
CMake build type defaults to None. Need to pass -DCMAKE_BUILD_TYPE=Release on the command-line.

https://github.com/gbdev/rgbds-www/blob/master/_installation/source.md (and RGBDS readme)

**Comment by ISSOtm** [comment]
Fixed by 4a6dfcdfc5c116b71c6bcee5718520dd72306a80 and gbdev/rgbds@4ce4fdec711df0c0f3af7ab955140161165716be.

**Comment by JL2210** [comment]
You only fixed it for CMake version 3.13 and above.
